command:
  "ruby --version":
    exit-status: 0
    stdout: [ /ruby \d+\.\d+/ ]
  "gem --version":
    exit-status: 0
    stdout: [ /\d+\.\d+/ ]
  "go version":
    exit-status: 0
    stdout: [ /go version go\d+\.\d+/ ]
  "lefthook version":
    exit-status: 0
    stdout: [ /\d+\.\d+/ ]
  "ast-grep --version":
    exit-status: 0
    stdout:
      - /\d+\.\d+/
  "opencode --version":
    exit-status: 0
    stdout:
      - /\d+\.\d+/

file:
  /usr/local/share/mise/installs/ruby:
    exists: true
    filetype: directory
  /usr/local/share/mise/installs/go:
    exists: true
    filetype: directory
  /usr/local/share/mise/installs/lefthook:
    exists: true
    filetype: directory
  /usr/local/share/mise/installs/ast-grep:
    exists: true
    filetype: directory
  /usr/local/bin/goose:
    exists: true
    filetype: file
    mode: "0755"
  /usr/local/bin/opencode:
    exists: true
    filetype: file
    mode: "0777"
  # Test npm global packages are installed (directories exist)
  /usr/local/share/mise/installs/node/24.8.0/lib/node_modules/@anthropic-ai/claude-code:
    exists: true
    filetype: directory
  /usr/local/share/mise/installs/node/24.8.0/lib/node_modules/@openai/codex:
    exists: true
    filetype: directory


