repos:
  - repo: local
    hooks:
      - id: renovate-validator
        name: Renovate Validator (Docker-only)
        entry: ./scripts/validate-renovate.sh --quick
        language: system
        files: '^\.github/renovate\.json5?$'
        pass_filenames: false
