name: Lint and Validate

on:
  push:
    branches: [main]
    paths-ignore: 
      - "docs/**"
      - "!docs/cookbooks/**/Dockerfile*"
      - "README.md"
      - "*.md"
  pull_request:
    branches: [main]
    paths-ignore: 
      - "docs/**"
      - "!docs/cookbooks/**/Dockerfile*"
      - "README.md"
      - "*.md"

jobs:
  hadolint:
    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint all Dockerfiles with Hadolint
        uses: jbergstroem/hadolint-gh-action@v1.13.0
        with:
          dockerfile: '**/Dockerfile*'
          config_file: '.hadolint.yaml'
          annotate: true

  yamllint:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3.0.2
        with:
          file_or_dir: "."
          config_file: ".yamllint"

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.66.0

      - name: Run Trivy security scan (Human-readable output)
        run: |
          echo "🔍 Running Trivy security scan..."
          trivy config --format table --severity HIGH,CRITICAL,MEDIUM .

      - name: Run Trivy security scan (SARIF for GitHub Security)
        run: |
          trivy config --format sarif --output trivy-results.sarif .

      - name: Run Trivy security scan (Fail on HIGH/CRITICAL)
        run: |
          echo "🔍 Running Trivy security scan with exit codes..."
          trivy config --exit-code 1 --severity HIGH,CRITICAL .

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"
